services:

  monitoring:
    image: ghcr.io/openads-project/monitoring:v1.0.0
    environment:
      # --- name ------
      NAMESPACE: /
      NAME: monitoring
      # --- other -----
      LOG_LEVEL: ${LOG_LEVEL:-info}
      USE_SIM_TIME: ${USE_SIM_TIME:-false}
      CONFIG: ${CONFIG:-}
    command:
      - /bin/bash
      - -ic
      - |
        ros2 launch monitoring monitoring.launch.py \
          namespace:=$${NAMESPACE} \
          name:=$${NAME} \
          log_level:=$${LOG_LEVEL} \
          use_sim_time:=$${USE_SIM_TIME} \
          config:=$${CONFIG}
